engines:
  eslint:
    enabled: true
    config:
      config: .eslintrc.json
  duplication:
    enabled: false
    config:
      languages:
      - javascript
ratings:
  paths:
  - "**.js"
exclude_paths:
- lib/
- test/**/*
- node_modules/**/
- Template/assets/
