language: node_js
sudo: false

node_js:
  - node

services:
  - postgresql

before_script:
  - npm install -g codeclimate-test-reporter
  - npm install -g codecov
  - npm install
  - psql -c 'create database recipestest;' -U postgres
  - sequelize db:migrate

env:
  global:
    - export NODE_ENV=test

cache:
  directories:
    - node_modules

after_success:
  - npm run coverage:all
  - codeclimate-test-reporter < coverage/lcov.info
