language: node_js
sudo: false
addons:
  code_climate:
    repo_token: 9e9a8782a28047259e7f1c8df7b2bb0545040fe84958586f96f82335bf88c289

node_js:
  - node

services:
  - postgresql

before_script:
  - psql -c 'create database recipestest;' -U postgres
  - sequelize db:migrate

env:
  global: 
    - export NODE_ENV=test
    - export SECRET_KEY = 'rEc1pEs-Âp1-1nada2la1'

cache:
  directories:
    - node_modules

script:
- npm install
- npm test
- npm run coveralls

after_script:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < ./coverage/lcov.info
