language: node_js
sudo: false

node_js:
  - node

services:
  - postgresql

before_script:
  - npm install -g codeclimate-test-reporter
  - psql -c 'create database recipestest;' -U postgres
  - sequelize db:migrate

env:
  global:
    - export NODE_ENV=test
    - export SECRET_KEY = 'rEc1pEs-Âp1-1nada2la1'

cache:
  directories:
    - node_modules

after_success:
  - npm run coverage
  - codeclimate-test-reporter < coverage/lcov.info
