language: node_js

node_js:
  - node

services:
  - postgresql

deploy:
  provider: heroku
  api_key:
    secure: "ea7eedab-016f-4fb6-a744-377186590205"

before_script:
  - npm install -g codeclimate-test-reporter

env:
  - NODE_ENV=test

after_success:
  - npm run coverage
  - codeclimate-test-reporter < coverage/lcov.info
      

  
