language: node_js
sudo: false

node_js:
  - node

services:
  - postgresql

before_script:
  - psql -c 'create database recipestest;' -U postgres
  - sequelize db:migrate

env:
  global: 
    - export NODE_ENV=test
    - export SECRET_KEY = 'rEc1pEs-Âp1-1nada2la1'

cache:
  directories:
    - node_modules

script:
- npm install
- npm test


after_success:
- npm run coveralls
