export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const CREATE_RECIPE = 'CREATE_RECIPE';
export const GET_USER_RECIPES = 'GET_USER_RECIPES';
export const GET_ALL_RECIPES = 'GET_ALL_RECIPES';
export const DELETE_RECIPE = 'DELETE_RECIPE';
